import { db } from '../db/connection'
import { jobs, subscribers } from '../db/schema'

const dummyJobs = [
  {
    title: 'Junior Frontend Developer',
    company: 'Productboard',
    link: 'https://jobs.cz/1',
    status: 'active',
    location: 'Praha – Karlín',
    source: 'jobs.cz',
    description: 'Hledáme junior frontend developera se znalostí React a TypeScript.',
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 29).toISOString(),
    clicks: 12,
    manuallyAdded: false,
    isDevRole: true,
    relevanceScore: 0.95,
    tags: JSON.stringify(['React', 'TypeScript', 'CSS']),
    salaryMin: 45000,
    salaryMax: 60000,
    workType: 'hybrid' as const,
    enrichmentStatus: 'done' as const,
    enrichedAt: new Date().toISOString(),
  },
  {
    title: 'Junior Backend Developer',
    company: 'Kiwi.com',
    link: 'https://jobs.cz/2',
    status: 'active',
    location: 'Brno',
    source: 'jobs.cz',
    description: 'Přidej se k našemu backend týmu, pracujeme s Python a PostgreSQL.',
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 10).toISOString(),
    clicks: 34,
    manuallyAdded: false,
    isDevRole: true,
    relevanceScore: 0.91,
    tags: JSON.stringify(['Python', 'PostgreSQL', 'Docker']),
    salaryMin: 50000,
    salaryMax: 65000,
    workType: 'remote' as const,
    enrichmentStatus: 'done' as const,
    enrichedAt: new Date().toISOString(),
  },
  {
    title: 'Junior Fullstack Developer',
    company: 'GoodData',
    link: 'https://prace.cz/1',
    status: 'active',
    location: 'Praha',
    source: 'prace.cz',
    description: 'React na frontendu, Node.js na backendu. Vítáme absolventy.',
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2).toISOString(),
    clicks: 7,
    manuallyAdded: false,
    isDevRole: true,
    relevanceScore: 0.88,
    tags: JSON.stringify(['React', 'Node.js', 'TypeScript']),
    salaryMin: null,
    salaryMax: null,
    workType: 'onsite' as const,
    enrichmentStatus: 'done' as const,
    enrichedAt: new Date().toISOString(),
  },
  {
    title: 'Junior Content Editor',
    company: 'Some Agency s.r.o.',
    link: 'https://prace.cz/2',
    status: 'active',
    location: 'Praha',
    source: 'prace.cz',
    description: 'Tvoř obsah pro sociální sítě a web.',
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 15).toISOString(),
    clicks: 0,
    manuallyAdded: false,
    isDevRole: false,
    relevanceScore: 0.05,
    tags: JSON.stringify([]),
    salaryMin: null,
    salaryMax: null,
    workType: 'unknown' as const,
    enrichmentStatus: 'done' as const,
    enrichedAt: new Date().toISOString(),
  },
  {
    title: 'Junior DevOps Engineer',
    company: 'Seznam.cz',
    link: 'https://jobs.cz/3',
    status: 'active',
    location: 'Praha – Smíchov',
    source: 'jobs.cz',
    description: 'Kubernetes, CI/CD, Linux. Praxe není nutná, zájem ano.',
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 29).toISOString(),
    clicks: 21,
    manuallyAdded: false,
    isDevRole: true,
    relevanceScore: 0.87,
    tags: JSON.stringify(['Kubernetes', 'Docker', 'Linux', 'CI/CD']),
    salaryMin: 55000,
    salaryMax: 70000,
    workType: 'hybrid' as const,
    enrichmentStatus: 'done' as const,
    enrichedAt: new Date().toISOString(),
  },
  {
    title: 'Junior QA Engineer',
    company: 'Gen Digital',
    link: 'https://jobs.cz/4',
    status: 'active',
    location: 'Praha – Centrum',
    source: 'jobs.cz',
    description:
      'Testování bezpečnostního softwaru, automatizace v Seleniu, spolupráce s vývojáři.',
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 20).toISOString(),
    clicks: 18,
    manuallyAdded: false,
    isDevRole: true,
    relevanceScore: 0.82,
    tags: JSON.stringify(['Selenium', 'Java', 'QA', 'Automation']),
    salaryMin: 40000,
    salaryMax: 55000,
    workType: 'hybrid' as const,
    enrichmentStatus: 'done' as const,
    enrichedAt: new Date().toISOString(),
  },
  {
    title: 'Junior Java Developer',
    company: 'Red Hat',
    link: 'https://jobs.cz/5',
    status: 'active',
    location: 'Brno',
    source: 'jobs.cz',
    description:
      'Pracuj na open-source projektech s moderním Java stackem. Ideální pro absolventy.',
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 25).toISOString(),
    clicks: 44,
    manuallyAdded: false,
    isDevRole: true,
    relevanceScore: 0.93,
    tags: JSON.stringify(['Java', 'Spring', 'Kubernetes', 'OpenShift']),
    salaryMin: 50000,
    salaryMax: 70000,
    workType: 'remote' as const,
    enrichmentStatus: 'done' as const,
    enrichedAt: new Date().toISOString(),
  },
  {
    title: 'Junior iOS Developer',
    company: 'Rohlik.com',
    link: 'https://prace.cz/4',
    status: 'active',
    location: 'Praha',
    source: 'prace.cz',
    description: 'Vyvíjej mobilní aplikaci pro miliony uživatelů. Swift, SwiftUI, Agile tým.',
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 14).toISOString(),
    clicks: 29,
    manuallyAdded: false,
    isDevRole: true,
    relevanceScore: 0.89,
    tags: JSON.stringify(['Swift', 'SwiftUI', 'iOS', 'Xcode']),
    salaryMin: 55000,
    salaryMax: 75000,
    workType: 'hybrid' as const,
    enrichmentStatus: 'done' as const,
    enrichedAt: new Date().toISOString(),
  },
  {
    title: 'Junior Data Analyst',
    company: 'Zonky',
    link: 'https://prace.cz/5',
    status: 'active',
    location: 'Remote',
    source: 'prace.cz',
    description: 'Analyzuj data z P2P platformy, tvoř reporty a dashboardy v Power BI.',
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 18).toISOString(),
    clicks: 9,
    manuallyAdded: false,
    isDevRole: false,
    relevanceScore: 0.61,
    tags: JSON.stringify(['SQL', 'Power BI', 'Excel', 'Python']),
    salaryMin: 38000,
    salaryMax: 50000,
    workType: 'remote' as const,
    enrichmentStatus: 'done' as const,
    enrichedAt: new Date().toISOString(),
  },
  {
    title: 'Junior .NET Developer',
    company: 'Česká spořitelna',
    link: 'https://jobs.cz/6',
    status: 'active',
    location: 'Praha – Holešovice',
    source: 'jobs.cz',
    description: 'Rozvoj bankovních systémů v C# a .NET. Zázemí velké české banky.',
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 22).toISOString(),
    clicks: 15,
    manuallyAdded: false,
    isDevRole: true,
    relevanceScore: 0.84,
    tags: JSON.stringify(['C#', '.NET', 'SQL Server', 'Azure']),
    salaryMin: 48000,
    salaryMax: 65000,
    workType: 'hybrid' as const,
    enrichmentStatus: 'done' as const,
    enrichedAt: new Date().toISOString(),
  },
  {
    title: 'Junior Cloud Engineer',
    company: 'Livesport',
    link: 'https://prace.cz/6',
    status: 'active',
    location: 'Praha – Žižkov',
    source: 'prace.cz',
    description: 'Spravuj cloudovou infrastrukturu pro jedny z největších sportovních webů světa.',
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7).toISOString(),
    clicks: 3,
    manuallyAdded: false,
    isDevRole: true,
    relevanceScore: 0.86,
    tags: JSON.stringify(['AWS', 'Terraform', 'Linux', 'Docker']),
    salaryMin: 52000,
    salaryMax: 68000,
    workType: 'onsite' as const,
    enrichmentStatus: 'done' as const,
    enrichedAt: new Date().toISOString(),
  },
  // Pending enrichment — simulates freshly scraped job
  {
    title: 'Programátor junior',
    company: 'Unknown s.r.o.',
    link: 'https://prace.cz/3',
    status: 'active',
    location: 'Ostrava',
    source: 'prace.cz',
    description: null,
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 29).toISOString(),
    clicks: 0,
    manuallyAdded: false,
    isDevRole: null,
    relevanceScore: null,
    tags: null,
    salaryMin: null,
    salaryMax: null,
    workType: null,
    enrichmentStatus: 'pending' as const,
    enrichedAt: null,
  },
]

const dummySubscribers = [
  {
    email: 'test@example.com',
    createdAt: new Date().toISOString(),
    confirmed: true,
  },
  {
    email: 'pending@example.com',
    createdAt: new Date().toISOString(),
    confirmed: false,
  },
]

export async function seed() {
  console.log('🌱 Seeding...')

  await db.insert(jobs).values(dummyJobs).onConflictDoNothing()
  ;(await db.insert(subscribers).values(dummySubscribers).onConflictDoNothing(),
    console.log(`✅ Inserted ${dummyJobs.length} jobs, ${dummySubscribers.length} subscribers`))
}
