import { db } from "../db/connection";
import { jobs, subscribers } from "../db/schema";

const dummyJobs = [
  {
    title: "Junior Frontend Developer",
    company: "Productboard",
    link: "https://jobs.cz/1",
    status: "active",
    location: "Praha – Karlín",
    source: "jobs.cz",
    description:
      "Hledáme junior frontend developera se znalostí React a TypeScript.",
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 29).toISOString(),
    clicks: 12,
    manuallyAdded: false,
    isDevRole: true,
    relevanceScore: 0.95,
    tags: JSON.stringify(["React", "TypeScript", "CSS"]),
    salaryMin: 45000,
    salaryMax: 60000,
    workType: "hybrid" as const,
    enrichmentStatus: "done" as const,
    enrichedAt: new Date().toISOString(),
  },
  {
    title: "Junior Backend Developer",
    company: "Kiwi.com",
    link: "https://jobs.cz/2",
    status: "active",
    location: "Brno",
    source: "jobs.cz",
    description:
      "Přidej se k našemu backend týmu, pracujeme s Python a PostgreSQL.",
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 10).toISOString(),
    clicks: 34,
    manuallyAdded: false,
    isDevRole: true,
    relevanceScore: 0.91,
    tags: JSON.stringify(["Python", "PostgreSQL", "Docker"]),
    salaryMin: 50000,
    salaryMax: 65000,
    workType: "remote" as const,
    enrichmentStatus: "done" as const,
    enrichedAt: new Date().toISOString(),
  },
  {
    title: "Junior Fullstack Developer",
    company: "GoodData",
    link: "https://prace.cz/1",
    status: "active",
    location: "Praha",
    source: "prace.cz",
    description: "React na frontendu, Node.js na backendu. Vítáme absolventy.",
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2).toISOString(),
    clicks: 7,
    manuallyAdded: false,
    isDevRole: true,
    relevanceScore: 0.88,
    tags: JSON.stringify(["React", "Node.js", "TypeScript"]),
    salaryMin: null,
    salaryMax: null,
    workType: "onsite" as const,
    enrichmentStatus: "done" as const,
    enrichedAt: new Date().toISOString(),
  },
  {
    title: "Junior Content Editor",
    company: "Some Agency s.r.o.",
    link: "https://prace.cz/2",
    status: "active",
    location: "Praha",
    source: "prace.cz",
    description: "Tvoř obsah pro sociální sítě a web.",
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 15).toISOString(),
    clicks: 0,
    manuallyAdded: false,
    isDevRole: false,
    relevanceScore: 0.05,
    tags: JSON.stringify([]),
    salaryMin: null,
    salaryMax: null,
    workType: "unknown" as const,
    enrichmentStatus: "done" as const,
    enrichedAt: new Date().toISOString(),
  },
  {
    title: "Junior DevOps Engineer",
    company: "Seznam.cz",
    link: "https://jobs.cz/3",
    status: "active",
    location: "Praha – Smíchov",
    source: "jobs.cz",
    description: "Kubernetes, CI/CD, Linux. Praxe není nutná, zájem ano.",
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 29).toISOString(),
    clicks: 21,
    manuallyAdded: false,
    isDevRole: true,
    relevanceScore: 0.87,
    tags: JSON.stringify(["Kubernetes", "Docker", "Linux", "CI/CD"]),
    salaryMin: 55000,
    salaryMax: 70000,
    workType: "hybrid" as const,
    enrichmentStatus: "done" as const,
    enrichedAt: new Date().toISOString(),
  },
  // Pending enrichment — simulates freshly scraped job
  {
    title: "Programátor junior",
    company: "Unknown s.r.o.",
    link: "https://prace.cz/3",
    status: "active",
    location: "Ostrava",
    source: "prace.cz",
    description: null,
    createdAt: new Date().toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 29).toISOString(),
    clicks: 0,
    manuallyAdded: false,
    isDevRole: null,
    relevanceScore: null,
    tags: null,
    salaryMin: null,
    salaryMax: null,
    workType: null,
    enrichmentStatus: "pending" as const,
    enrichedAt: null,
  },
];

const dummySubscribers = [
  {
    email: "test@example.com",
    createdAt: new Date().toISOString(),
    confirmed: true,
  },
  {
    email: "pending@example.com",
    createdAt: new Date().toISOString(),
    confirmed: false,
  },
];

export async function seed() {
  console.log("🌱 Seeding...");

  await db.insert(jobs).values(dummyJobs).onConflictDoNothing();
  (await db.insert(subscribers).values(dummySubscribers).onConflictDoNothing(),
    console.log(
      `✅ Inserted ${dummyJobs.length} jobs, ${dummySubscribers.length} subscribers`,
    ));
}
