services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      args:
        - DB_FILENAME=/app/data/db.sqlite
    restart: unless-stopped
    environment:
      - NODE_ENV=PRODUCTION
      - PORT=8080
      - DB_FILENAME=/app/data/db.sqlite
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - /home/andy/data:/app/data
    networks:
      - internal

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.praceprojuniora.cz
      - INTERNAL_API_URL=http://api:8080
    depends_on:
      - api
    networks:
      - internal

networks:
  internal:
    driver: bridge
