// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_listings from "./routes/api/listings.ts";
import * as $index from "./routes/index.tsx";
import * as $job_list from "./islands/job-list.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/listings.ts": $api_listings,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/job-list.tsx": $job_list,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
