// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_listings_click from "./routes/api/listings/click.ts";
import * as $api_listings_index from "./routes/api/listings/index.ts";
import * as $api_listings_new from "./routes/api/listings/new.ts";
import * as $index from "./routes/index.tsx";
import * as $app_components_about from "./islands/app/_components/about.tsx";
import * as $app_components_list_item from "./islands/app/_components/list-item.tsx";
import * as $app_components_list from "./islands/app/_components/list.tsx";
import * as $app_components_search_list from "./islands/app/_components/search-list.tsx";
import * as $app_index from "./islands/app/index.tsx";
import * as $job_list from "./islands/job-list.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/listings/click.ts": $api_listings_click,
    "./routes/api/listings/index.ts": $api_listings_index,
    "./routes/api/listings/new.ts": $api_listings_new,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/app/_components/about.tsx": $app_components_about,
    "./islands/app/_components/list-item.tsx": $app_components_list_item,
    "./islands/app/_components/list.tsx": $app_components_list,
    "./islands/app/_components/search-list.tsx": $app_components_search_list,
    "./islands/app/index.tsx": $app_index,
    "./islands/job-list.tsx": $job_list,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
